---
- hosts: dev 
  become: true 
  tasks:
    - name: create a file on all the dev servers
      file:
        path: /home/bewah/students
        state: touch 
        mode: 0600
        owner: bewah
        group: bewah
...
