---
- hosts: all
  become: true 
  tasks:
    - name: create a directory  called court-cases on all  servers
      file:
        path: /home/bewah/court-cases
        state: directory 
        mode: 000
        owner: root
        group: root
...
