- hosts: all 
  become: yes
  tasks:
  - name: Create Systems admin  User
    user:
      name: joyce
      create_home: true
      shell: /bin/bash
      comment: "joyce Management Account"
      expires: -1
      password: "{{ 'DevOps@2020' | password_hash('sha512','A512') }}"
  - name: Setup Sudo Access for Devops User
    copy:
      dest: /etc/sudoers.d/joyce
      content: 'joyce ALL=(ALL) NOPASSWD: ALL' 
      validate: /usr/sbin/visudo -cf %s
  -  name: Disable Password Authentication
     lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PasswordAuthentication'
        line="PasswordAuthentication yes"
        state=present
        backup=yes
     notify:
       - restart ssh
  handlers:
  - name: restart ssh
    service:
      name=sshd
      state=restarted